# ========================
# SonarCloud Configuration
# ========================

sonar.projectKey=rujleon_qualimetrie-audit
sonar.organization=rujleon

# Sources et tests
sonar.sources=.
sonar.tests=**/*.test.js

# Exclusions
sonar.exclusions=node_modules/**,.github/**,coverage/**,lcov-report/**,dist/**,build/**
sonar.coverage.exclusions=**/*.config.js,**/coverage/**,**/*.spec.js

# Couverture Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8